services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/static:/etc/nginx/static
      - ./certs:/certs:ro
    networks:
      - homepage-app-network
    depends_on:
      - homepage
      - api
  homepage:
    image: nyttevaerdien/homepage-frontend:2.0.0
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - homepage-app-network
    depends_on:
      - api
  api:
    image: nyttevaerdien/homepage-api:2.0.0
    container_name: api
    restart: unless-stopped
    volumes:
      - "./db:/db"
    ports:
      - "8080:8080"
    networks:
      - homepage-app-network
networks:
  homepage-app-network:
    driver: bridge
