services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/static:/etc/nginx/static
      - ./certs:/certs:ro
    networks:
      - homepage-app-network
    depends_on:
      - frontend
      - api
  frontend:
    image: nyttevaerdien/homepage-frontend:2.1.0
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - homepage-app-network
    depends_on:
      - api
  api:
    image: nyttevaerdien/homepage-api:2.1.0
    container_name: api
    restart: unless-stopped
    volumes:
      - "./db:/db"
    ports:
      - "8080:8080"
    environment:
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
    networks:
      - homepage-app-network
networks:
  homepage-app-network:
    driver: bridge
